version: '3.1'
services:
  web_api:
    build: ./web_api
    ports:
      - "4000:4000"
    volumes:
      - ./web_api:/code
    depends_on:
      - db
    command: mix phoenix.server

  websocket_server:
    build: ./websocket_server
    ports:
      - "5000:5000"
    volumes:
      - ./websocket_server:/code
    command: mix phoenix.server

  db:
    image: postgres

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html

  rabbitmq:
    image: rabbitmq:3.6.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  visualizer:
    image: dockersamples/visualizer
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
