version: '3.1'
services:
  web_api:
    image: klotzandrew/superturbowidgetexchange3_web_api
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: mix phoenix.server

  websocket_server:
    image: klotzandrew/superturbowidgetexchange3_websocket_server
    ports:
      - "5000:5000"
    command: mix phoenix.server

  db:
    image: postgres

  frontend:
    image: klotzandrew/superturbowidgetexchange3_frontend
    ports:
      - "80:80"

  haproxy:
    image: superturbowidgetexchange3_haproxy

  rabbit-1:
    image: klotzandrew/superturbowidgetexchange3_rabbit-1
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=abcdefg
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODENAME=rabbit@rabbit-1
      - RABBITMQ_CLUSTER_NODES=rabbit@rabbit-2
      - RABBITMQ_SETUP_DELAY=0

  rabbit-2:
    image: klotzandrew/superturbowidgetexchange3_rabbit-1
    environment:
      - RABBITMQ_ERLANG_COOKIE=abcdefg
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODENAME=rabbit@rabbit-2
      - RABBITMQ_CLUSTER_NODES=rabbit@rabbit-1
      - RABBITMQ_SETUP_DELAY=30
    ports:
      - "5674:5672"
      - "15674:15672"

  visualizer:
    image: dockersamples/visualizer
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
