version: '3.1'
services:
  web_api:
    build: ./web_api
    ports:
      - "4000:4000"
    volumes:
      - ./web_api:/code
    depends_on:
      - db
    command: mix phoenix.server

  websocket_server:
    build: ./websocket_server
    ports:
      - "5000:5000"
    volumes:
      - ./websocket_server:/code
    command: mix phoenix.server

  db:
    image: postgres

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html

  haproxy:
    build: ./haproxy

  rabbit-1:
    build: ./rabbit
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=abcdefg
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODENAME=rabbit@rabbit-1
      - RABBITMQ_CLUSTER_NODES=rabbit@rabbit-2
      - RABBITMQ_SETUP_DELAY=0

  rabbit-2:
    build: ./rabbit
    environment:
      - RABBITMQ_ERLANG_COOKIE=abcdefg
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODENAME=rabbit@rabbit-2
      - RABBITMQ_CLUSTER_NODES=rabbit@rabbit-1
      - RABBITMQ_SETUP_DELAY=30
    ports:
      - "5674:5672"
      - "15674:15672"

  visualizer:
    image: dockersamples/visualizer
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
