version: '3.1'
services:
  web_api:
    build: ./web_api
    ports:
      - "4000:4000"
    volumes:
      - ./web_api:/code
    depends_on:
      - db
    command: mix phoenix.server

  db:
    image: postgres
