export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_ACCOUNT_WIDGETS = 'SET_ACCOUNT_WIDGETS';
export const RECORD_SENT_WIDGET = 'RECORD_SENT_WIDGET';
export const RECORD_RECEIVED_WIDGET = 'RECORD_RECEIVED_WIDGET';
